### ISSUE TITLE
UnicodeDecodeError...

### ISSUE THREAD

**Issue by Joqui2108** [Zulko/twittcher#1]
I was doing some tests with the bot when the error `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 120: ordinal not in range(128)` appear.

I looked upon the internet to see if I could debbug it, but it's more powerful than me.
Hope this could help you: http://farmdev.com/talks/unicode/

**Comment by Zulko** [comment]
Thanks for the feedback. Can you paste the whole error so that I can see where it happens ? Could you also paste the code ?

**Comment by Joqui2108** [comment]
The code is this:

from twittcher import SearchWatcher

bot = SearchWatcher("TLOU", database="database.db")
bot.watch_every(48)

and the hole error is this:

http://pastebin.com/BYVYmFvJ

**Comment by Zulko** [comment]
This works on my computer, maybe it was a tweet with a strange character... I will investigate.

**Comment by Joqui2108** [comment]
Yes, it should be it. Because of the accents and things like that.
It could be a problem with the compatibility of the OS language encoding and the parsed tweets encoding.

**Comment by Joqui2108** [comment]
With the latest commit it's fixed! Thanks
